name: build and release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple

  build:
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Build Pylon resource pack
        working-directory: pylon-resource-pack
        run: |
          python resource_pack_generator.py

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Build resource pack
        run: bun .
      
      # Push artifacts to GitHub actions
      - name: Upload resource pack artifact
        uses: actions/upload-artifact@v4
        with:
          name: PylonSlimefun
          path: PylonSlimefun/

      - name: Upload release asset
        # Use the GitHub CLI to upload the file to the newly created release
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} PylonSlimefun.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The built-in token has permission for this