name: Check PylonPack update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  detect-submodule:
    runs-on: ubuntu-latest
    outputs:
      submodule_changed: ${{ steps.check.outputs.submodule_changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - id: check
        name: Check for submodule changes
        run: |
          git submodule update --remote --merge
          if git diff --quiet pylon-resource-pack; then
            echo "submodule_changed=false" >> $GITHUB_OUTPUT
          else
            echo "submodule_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Push updated submodule pointer
        if: steps.check.outputs.submodule_changed == 'true'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add pylon-resource-pack
          git commit -m "Update submodule to latest commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}